# Generated by Django 5.1.1 on 2025-03-29 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('name_rol', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('idType_document', models.AutoField(primary_key=True, serialize=False)),
                ('name_document', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_user', models.BigIntegerField(unique=True)),
                ('email', models.TextField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('contact_two', models.BigIntegerField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
                ('idType_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.typedocument')),
            ],
        ),
    ]
