# Generated by Django 5.1.7 on 2025-05-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campana', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('ID_Estado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('name_rol', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('idType_document', models.AutoField(primary_key=True, serialize=False)),
                ('name_document', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document_user', models.BigIntegerField(unique=True)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('contact_two', models.BigIntegerField()),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
                ('idType_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.typedocument')),
                ('id_estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado')),
            ],
        ),
    ]
