# Generated by Django 5.1.7 on 2025-05-13 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado'),
        ),
    ]
