# Generated by Django 5.1.7 on 2025-04-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('ID_Estado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
