# Generated by Django 5.1.7 on 2025-05-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_campana_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='marca_diadema',
            fields=[
                ('id_marca_diadema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca_diadema', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
