# Generated by Django 5.1.7 on 2025-04-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado'),
        ),
    ]
