# Generated by Django 5.1.7 on 2025-04-24 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado'),
        ),
    ]
