# Generated by Django 5.1.7 on 2025-05-14 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_empleado_cedula_alter_empleado_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaDiadema',
            fields=[
                ('id_acta_diadema', models.AutoField(primary_key=True, serialize=False)),
                ('serial_diadema', models.CharField(max_length=50, unique=True)),
                ('precio_diadema', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.campana')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
                ('marca_diadema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.marca_diadema')),
            ],
        ),
    ]
