# Generated by Django 5.1.7 on 2025-05-14 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_actadiadema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEquipo',
            fields=[
                ('id_acta_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('serial_proveedor_cpu', models.CharField(max_length=100)),
                ('serial_fabrica_cpu', models.CharField(max_length=100)),
                ('serial_proveedor_monitor', models.CharField(max_length=100)),
                ('serial_fabrica_monitor', models.CharField(max_length=100)),
                ('teclado', models.BooleanField(default=False)),
                ('mouse', models.BooleanField(default=False)),
                ('monitor', models.BooleanField(default=False)),
                ('cable_poder', models.BooleanField(default=False)),
                ('adaptador_corriente', models.BooleanField(default=False)),
                ('cable_video', models.BooleanField(default=False)),
                ('cable_red', models.BooleanField(default=False)),
                ('bolso', models.BooleanField(default=False)),
                ('cargador', models.BooleanField(default=False)),
                ('base', models.BooleanField(default=False)),
                ('guaya', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.campana')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor')),
            ],
        ),
    ]
