# Generated by Django 5.1.7 on 2025-05-07 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_user_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id_campana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_campana', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Inhabilitado', 'Inhabilitado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.campana')),
            ],
        ),
    ]
