# Generated by Django 5.1.7 on 2025-05-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_actaequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorActa',
            fields=[
                ('id_ProveedorActa', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden_instalacion', models.CharField(max_length=50)),
                ('numero_pedido', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('empresa', models.CharField(default='BRM S.A.S', max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('equipo', models.CharField(max_length=100)),
                ('procesador', models.CharField(max_length=100)),
                ('ram_gb', models.IntegerField()),
                ('disco_duro_tb', models.FloatField()),
                ('dvd_writer', models.BooleanField(default=False)),
                ('entregado_por', models.CharField(max_length=100)),
                ('recibido_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.proveedor')),
            ],
        ),
    ]
