# Generated by Django 5.1.7 on 2025-05-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_proveedoracta'),
    ]

    operations = [
        migrations.AddField(
            model_name='actadiadema',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='actas_diadema/'),
        ),
    ]
