# Generated by Django 5.1.7 on 2025-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_actadiadema_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedoracta',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='actas_proveedor/'),
        ),
    ]
