# Generated by Django 5.1.7 on 2025-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_proveedoracta_archivo_adjunto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedoracta',
            name='archivo_adjunto',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_proveedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
