# Generated by Django 5.1.7 on 2025-05-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_proveedoracta_archivo_adjunto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actadiadema',
            name='archivo',
        ),
    ]
